table Diim_Location
	lineageTag: 2f8a9e45-2fce-4c0a-8ff6-deb3b625f9cb

	column location_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 52509595-0ec9-41af-9041-6d16b5d0b461
		summarizeBy: none
		sourceColumn: location_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column borough
		dataType: string
		lineageTag: 5ead5ab8-e55e-4152-8a21-e919c95dc78d
		summarizeBy: none
		sourceColumn: borough

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: b0bd5ab9-d9e7-4715-a1ba-38720e77d265
		summarizeBy: none
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column longitude
		dataType: double
		lineageTag: 6ffa7e5e-22d1-45e0-b882-c300b020723e
		summarizeBy: none
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Diim_Location = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = Sql.Database("t52pq5prlkturgp6ra5mlc3vqa-ooolzdhsejqufjqk5gl7v4lqx4.datawarehouse.fabric.microsoft.com", "NYC311_Lakehouse"),
				    dbo_gold_dim_location = Source{[Schema="dbo",Item="gold_dim_location"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_gold_dim_location,{"city"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

